### ISSUE TITLE
Assignmeny tasks

### ISSUE THREAD

**Issue by Kayeeec** [Kayeeec/tron#4]
### Task 1

- [x] Make  it  possible  to  add  more  players  to  TRON  easily  (so  3,4,5. . . people  can  play  at  the same time each with their own uniquely coloured bike)
- [x] Addition or removal of players should be as simple as possible, take into account the collision detection, controls configuration, rendering etc.
- [x] Addition of player will be done offline, that is to change number of players the source of the game will be altered and the whole code recompiled.  There is no need to create any kind of game menu.

### Task 2

- [x] Adapt current code to make it possible to use as much of it as possible as a generic engine for implementing other games.
- [x] Provide a way for these new implementations to bind with the engine, e.g.  interfaces that need to be implemented.
- [x] Make the current TRON game such implementation of the engine.

### Task 3

- [x] Add the possibility to control any player by mouse (e.g.  turn left or right using left and right mouse buttons respectively

### Task 4

- [x] Separate the state of the game from its graphical representation,  that is have one class /package represent the Model and other the Presentation.
- [x] The model must contain and provide access for the player bikes, events such as  collision between two players happened and so forth.
- [x] There is no dependency from Model to Presentation, only from Presentation to Model
- [x] The model itself should not handle frame timing (Thread.sleep()), that is the responsibility of  calling some update method on the model is outside of the model, preferably in the extracted engine code from previous tasks

### Task 5

- [ ] Use the extracted engine to implement some other game (e.g.  pong, snake,...)

### Task 6

- [ ] Use git for your solution and structure your commits in a similar way to the demo/exercise,i.e.  the commits represent the individual steps in the refactoring process
